set nocp "nekompalita se starými vi
filetype plugin indent on "odsazování podle typu souboru
set backspace=indent,eol,start "backspace maže vše
set background=dark " lepší čitelnost na tmavém pozadí
set t_Co=256
syntax on "zvýraznění syntaxe
colorscheme calmar256-dark
set display=lastline "zobrazovat alespoň část řádku místo zavináčů
set ignorecase "case insensitive vyhledávání
set smartcase "vypne case insensitive při hledání slova s velkými písmeny
set incsearch "při hledání hned zobrazuje prvně nálezené
set nojoinspaces "nevkládá dvě mezery za větu při spojování řádků
set number "číslování řádků
set ruler "zobrazení pozice v dokumentu 
set scrolloff=4 "počet řádků které mají být vidět před a za kurzorem
set showbreak=\\ "označení zalomených řádků
set showcmd "zobrazuje zadávaný přikaz
set showmatch "zapíšete-li pravou závorku, ukáže vám její protějšek
set showmode "zobrazuje --INSERT--
set tabstop=2 "velikost tab
set shiftwidth=2 "velikost odsazování
set title "zobrazování informací v titulku okna
set viminfo='50,r/mnt,n~/.vim/viminfo "ukládání historie 
set wildignore=*~,*.bak "při doplňování bude ignorováno
set wildmenu "při <Tab> zobrazí možnosti
set wildmode=longest,list "způsob doplňování 
set wrap "zalamování řádků
set spelllang=cs
set spell
set fileencodings=utf-8,iso-8859-2,windows-1250

set cursorline
hi cursorline cterm=none term=none
autocmd WinEnter * setlocal cursorline
autocmd WinLeave * setlocal nocursorline
highlight CursorLine guibg=#303000 ctermbg=234

highlight clear SpellBad
highlight SpellBad term=standout ctermfg=1 term=underline cterm=underline
highlight clear SpellCap
highlight SpellCap term=underline cterm=underline
highlight clear SpellRare
highlight SpellRare term=underline cterm=underline
highlight clear SpellLocal
highlight SpellLocal term=underline cterm=underline

let html_number_lines = 0 "nastavení 2html
let html_use_css = 1 "nastavení 2html
set directory=~/tmp "dočasné soubory do tmp a ne do aktuálního adresáře

"klávesové zkratky
imap <C-d> <Del>
imap <C-a> <C-b>
cmap <C-d> <Del>
cmap <C-a> <C-b>

"trocha klávesových zkratek pro HTML
let maplocalleader = "," 
imap <LocalLeader>< &lt;
imap <LocalLeader>> &gt;
imap <LocalLeader>& &amp;
imap <LocalLeader>n &nbsp;
imap <C-t> <></><Esc>5hdiwp3lpT>i
imap <LocalLeader>tab <table><CR><tr><CR><td></td><CR></tr><CR></table>

function! HTML_anchor()
let cil = input("Cíl odkazu: ")
let popisek = input("Popisek odkazu: ")
execute "normal a<a href=\"".cil."\" title=\"".popisek."\"></a>"
execute "normal 3h"
:startinsert
endfunction

imap <LocalLeader>a <Esc>:call HTML_anchor()<CR>

augroup crypto
	au!
	autocmd BufReadPre,FileReadPre		/mnt/crypto/* set viminfo=
	autocmd BufReadPre,FileReadPre		/mnt/crypto/* set noswapfile
augroup END
